### ISSUE TITLE
Make new release after moving the package to GitHub

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/rcwa#3]
This is now in progress in #4.

**Comment by olexandr-konovalov** [comment]
Completed in #5 and 82c1773a1718cdbf071515e6aca86a0fd73fced3

**Comment by Stefan-Kohl** [comment]
@alex-konovalov If the RCWA manual is now built using AutoDoc(?), then the (now broken) function RCWABuildManual and its documentation should probably be removed. The same likely holds for the function ResClassesBuildManual in ResClasses.

**Comment by olexandr-konovalov** [comment]
Thanks - I have created new issues for this task, otherwise making a suggestion in a comment under a closed issue is the best way to ensure that it will be abandoned for a long time.
